### PR TITLE
Added support for RTSP

### PR DESCRIPTION
**Pull request by bartekpacia**
I'm making a PR for changes made by @e1z0 in [his issue](https://github.com/brutella/hkcam/issues/95). 

It works really great

### CODE REVIEW

**Comment by bartekpacia** [comment]
please @brutella, review this

**Comment by bartekpacia** [comment]
: (

**Comment by brutella** [comment]
Sorry for not looking into this so far. Your pull request results in a lot of duplicated code. It would be great if we could fix that.

Could you please summarise which FFmpeg options have to be changed to make RTSP work. Thanks.

**Comment by tomtastic** [comment]
Hi @bartekpacia, will you have time to resolve these questions, I'd love to see your work merged here :)

**Comment by bartekpacia** [comment]
Hahah, I totally forgot about this PR. Will look today into it.

**Comment by bartekpacia** [comment]
Actually what I did in this PR is only apply a patch from @e1z0 that he shared [in this issue](https://github.com/brutella/hkcam/issues/95). I didn't write this code myself. Also, I see that some merge conflicts arose.

@tomtastic Feel free to pick up this PR and create a new one.

**Pull request closed without merging**
